// Back-of-body massage routine, prone position. 15 techniques, 60 minutes total.
// Region codes match SVG highlight IDs in index.html.
// imageFile is loaded from the images/ folder; missing files gracefully fall back to the silhouette.
const ROUTINE = [
  {
    region: "Scalp",
    regionId: "scalp",
    technique: "Circular Fingertip Pressure",
    description: "Cradle the head with both hands. Use the pads of your fingertips to make small, slow circles across the entire scalp — sides, crown, base of skull. Keep pressure firm but gentle, moving the scalp itself rather than sliding over the hair.",
    durationSec: 4 * 60,
    imageFile: "images/01-scalp.png",
  },
  {
    region: "Back of Neck",
    regionId: "neck",
    technique: "Squeeze and Glide",
    description: "Gently turn the head to one side or have them rest on a pillow. Cup the back of the neck with one hand and squeeze the muscles on either side of the spine, gliding from the base of the skull down to the shoulders. Repeat slowly several times each side.",
    durationSec: 3 * 60,
    imageFile: "images/02-neck.png",
  },
  {
    region: "Shoulders",
    regionId: "shoulders",
    technique: "Kneading the Trapezius",
    description: "Stand at the head of the recipient. Place your palms over the tops of the shoulders, fingers in front, thumbs behind. Slowly knead the trapezius muscle between fingers and thumbs, working from the neck out to the shoulder tips. Linger on any knots.",
    durationSec: 4 * 60,
    imageFile: "images/03-shoulders.png",
  },
  {
    region: "Upper Back",
    regionId: "upper-back",
    technique: "Long Strokes Around the Shoulder Blades",
    description: "Apply oil if using. Glide both palms outward from the spine, tracing around each shoulder blade in long sweeping arcs. Use moderate pressure on the outward stroke and a light return. Repeat in flowing motion.",
    durationSec: 4 * 60,
    imageFile: "images/04-upper-back.png",
  },
  {
    region: "Spine",
    regionId: "spine",
    technique: "Thumb Walk Along the Paraspinals",
    description: "Place your thumbs on either side of the spine (never on the bone itself) just below the neck. Press, release, and step thumbs down half an inch at a time, all the way to the lower back. Repeat the journey two or three times.",
    durationSec: 4 * 60,
    imageFile: "images/05-spine.png",
  },
  {
    region: "Mid Back",
    regionId: "mid-back",
    technique: "Palm Circles",
    description: "Lay both palms flat on the mid-back. Make large, slow, overlapping circles, letting your body weight provide the pressure. Cover the area between the shoulder blades and the lower ribs.",
    durationSec: 4 * 60,
    imageFile: "images/06-mid-back.png",
  },
  {
    region: "Lower Back",
    regionId: "lower-back",
    technique: "Circles and Gentle Kneading",
    description: "Use both palms to make broad circles across the lower back, then switch to kneading the soft tissue on either side of the spine between thumb and fingers. Avoid direct pressure on the spine itself. Stay slow and steady.",
    durationSec: 5 * 60,
    imageFile: "images/07-lower-back.png",
  },
  {
    region: "Glutes & Hips",
    regionId: "glutes",
    technique: "Kneading and Compression",
    description: "Use the heels of your palms to press into the glute muscles in slow, deep compressions. Alternate with kneading using both hands. These muscles hold a lot of tension — don't be afraid to use firm pressure.",
    durationSec: 5 * 60,
    imageFile: "images/08-glutes.png",
  },
  {
    region: "Left Hamstring",
    regionId: "left-hamstring",
    technique: "Long Strokes and Kneading",
    description: "Move to the recipient's left side. Glide both palms up the back of the thigh from knee to glute. After several strokes, knead the hamstring muscle between your hands. Avoid pressing into the back of the knee.",
    durationSec: 4 * 60,
    imageFile: "images/09-left-hamstring.png",
  },
  {
    region: "Right Hamstring",
    regionId: "right-hamstring",
    technique: "Long Strokes and Kneading",
    description: "Move to the recipient's right side and repeat the hamstring sequence: long sweeping strokes from knee to glute, then kneading. Match the rhythm and pressure of the left side.",
    durationSec: 4 * 60,
    imageFile: "images/10-right-hamstring.png",
  },
  {
    region: "Calves",
    regionId: "calves",
    technique: "Squeeze and Glide Both Calves",
    description: "Wrap your hands around one calf at a time. Squeeze gently and glide from the ankle up toward the back of the knee, then release pressure on the return. Spend equal time on each leg. Keep pressure moderate — calves can be tender.",
    durationSec: 5 * 60,
    imageFile: "images/11-calves.png",
  },
  {
    region: "Left Foot",
    regionId: "left-foot",
    technique: "Thumb Circles on Sole, Glide Each Toe",
    description: "Cradle the left foot. Use both thumbs to press deep, slow circles into the arch and ball of the foot. Then gently pull and glide each toe one at a time. Finish with a long stroke from heel to toes.",
    durationSec: 4 * 60,
    imageFile: "images/12-left-foot.png",
  },
  {
    region: "Right Foot",
    regionId: "right-foot",
    technique: "Thumb Circles on Sole, Glide Each Toe",
    description: "Repeat the same foot sequence on the right side: thumb circles on the sole, attention to the arch and ball, then a gentle pull on each toe. End with a long heel-to-toe stroke.",
    durationSec: 4 * 60,
    imageFile: "images/13-right-foot.png",
  },
  {
    region: "Full Body",
    regionId: "full-body",
    technique: "Long Sweep, Neck to Feet",
    description: "Standing at the head, place both palms on the upper back. Glide in one long, continuous stroke down the back, over the glutes, down the legs, all the way to the feet. Repeat several times — slow, light, and connecting.",
    durationSec: 3 * 60,
    imageFile: "images/14-full-body-sweep.png",
  },
  {
    region: "Full Body",
    regionId: "full-body",
    technique: "Closing Rest Hold",
    description: "Place one hand softly on the upper back between the shoulder blades and the other on the lower back. Hold still. Let the recipient feel grounded and complete. Breathe slowly. When ready, let them know the massage is finished.",
    durationSec: 3 * 60,
    imageFile: "images/15-rest-hold.png",
  },
];
